default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: flux_tutorial_development

test:
  <<: *default
  database: flux_tutorial_test

production:
  <<: *default
  database: flux_tutorial_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket:   /var/lib/mysql/mysql.sock
